--- 
- name: "playing with conditions"
  hosts: localhost 
  vars: 
    - tableau: [1, 2, 4, 5, 2]
    - tableau_2 : [6, 7, 8, 9,  2, 4]
    - patate: macabo  
  tasks: 
    - name: "playing with ansible_facts"
      debug: 
        var: ansible_facts.os_family 
    - ansible.builtin.include_tasks: "{{ ansible_facts.os_family | lower }}.yml"
        
    - name: "conditions"
      file: 
        path: /home/haruna/stevy/harounadir
        state: directory
        mode: '0755'
      when: 
        - ansible_facts.os_family | lower == "redhat" 
        - ansible_facts.distribution | upper == "FEDORA"
      
        
  